[versions]

conscrypt-openjdk = "2.5.2"
groovy = "4.0.8"
junit = '5.9.2'
kotlin = "1.8.10"
kotlin-coroutines = "1.6.4"
kotest-runner = '5.5.5'
protobuf-java = '3.21.12'
spock = "2.3-groovy-4.0"
testcontainers = '1.17.6'

micronaut = '4.0.0-SNAPSHOT'
micronaut-docs = '2.0.0'
micronaut-gradle-plugin = '3.7.2'

micronaut-grpc = "4.0.0-SNAPSHOT"
micronaut-multitenancy = "5.0.0-SNAPSHOT"
micronaut-reactor = "3.0.0-SNAPSHOT"
micronaut-serde = "2.0.0-SNAPSHOT"
micronaut-test = '4.0.0-SNAPSHOT'

managed-pulsar-client = '2.11.0'

[libraries]
# Micronaut BOMS
micronaut-grpc = { module = "io.micronaut.grpc:micronaut-grpc-bom", version.ref = "micronaut-grpc" }
micronaut-multitenancy = { module = "io.micronaut.multitenancy:micronaut-multitenancy-bom", version.ref = "micronaut-multitenancy" }
micronaut-reactor = { module = "io.micronaut.reactor:micronaut-reactor-bom", version.ref = "micronaut-reactor" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }

# Managed libraries
managed-pulsar-client = { module = 'org.apache.pulsar:pulsar-client-original', version.ref= 'managed-pulsar-client' }

# Other libraries
conscrypt-openjdk = { module = "org.conscrypt:conscrypt-openjdk-uber", version.ref="conscrypt-openjdk" }
kotlin-coroutines = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-core', version.ref = 'kotlin-coroutines' }
kotlin-reflect = { module = 'org.jetbrains.kotlin:kotlin-reflect', version.ref = 'kotlin' }
kotlin-stdlib-jdk8 = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk8', version.ref = 'kotlin' }
kotlinx-coroutines-core = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-core', version.ref = 'kotlin-coroutines' }
kotlinx-coroutines-jvm = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm', version.ref = 'kotlin-coroutines' }
kotlinx-coroutines-jdk8 = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-jdk8', version.ref = 'kotlin-coroutines' }
protobuf-java = { module = 'com.google.protobuf:protobuf-java', version.ref = 'protobuf-java' }

junit-jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api', version.ref = 'junit' }
kotest-runner = { module = 'io.kotest:kotest-runner-junit5', version.ref = 'kotest-runner' }
testcontainers = { module = 'org.testcontainers:testcontainers', version.ref = 'testcontainers' }
testcontainers-spock = { module = 'org.testcontainers:spock', version.ref = 'testcontainers' }
testcontainers-pulsar = { module = 'org.testcontainers:pulsar', version.ref = 'testcontainers' }

micronaut-docs = { module = "io.micronaut.docs:micronaut-docs-asciidoc-config-props", version.ref = "micronaut-docs" }

gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

